version: "3.1"
services:
  #  mysql:
  #    image: mysql:latest
  #    container_name: s_mysql
  #    restart: on-failure
  #    command: --default-authentication-plugin=mysql_native_password
  #    ports:
  #      - 3306:3306
  #    environment:
  #      MYSQL_DATABASE: scms
  #      MYSQL_ROOT_PASSWORD: secret

  pgsql:
    image: postgres:11.3-alpine
    container_name: s_pgsql
    restart: on-failure
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: scms
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret

  redis:
    image: redis:alpine
    container_name: s_redis
    restart: on-failure
    ports:
      - 6379:6379
    sysctls:
      net.core.somaxconn: "65535"

  fpm:
    build: php-fpm
    container_name: s_fpm
    working_dir: /app
    restart: on-failure
    volumes:
      - ../:/app:Z

  nginx:
    image: nginx:alpine
    container_name: s_nginx
    working_dir: /app
    restart: on-failure
    volumes:
      - ../:/app:Z
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8000:80
